# Generated by Django 3.2.15 on 2023-01-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_application_rsvp"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="conduct_agree",),
        migrations.RemoveField(model_name="application", name="data_agree",),
        migrations.RemoveField(model_name="application", name="q1",),
        migrations.RemoveField(model_name="application", name="q2",),
        migrations.RemoveField(model_name="application", name="q3",),
        migrations.AddField(
            model_name="application",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("Halal", "halal"),
                    ("Vegetarian", "vegetarian"),
                    ("Gluten-Free", "gluten-free"),
                    ("Other but Specify", "other but specify"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="how_many_hackathons",
            field=models.TextField(
                choices=[
                    (None, ""),
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5 or more", "5 or more"),
                ],
                default="",
                help_text="How many hackathons have you been to?",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="program",
            field=models.CharField(
                default="", help_text="Program or Major", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="referral_source",
            field=models.TextField(
                default="",
                help_text="How did you hear about CoolHacks?",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="resume_sharing",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I consent to IEEE UofT sharing my resume with event sponsors.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tshirt_size",
            field=models.CharField(
                choices=[(None, ""), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="what_hackathon_experience",
            field=models.TextField(
                default="",
                help_text="If you’ve been to a hackathon, briefly tell us your experience. If not, describe what you expect to see and experience. (200 words max)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="what_technical_experience",
            field=models.TextField(
                default="",
                help_text="What is your technical experience with software and hardware? (200 words max)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="why_participate",
            field=models.TextField(
                default="",
                help_text="Why do you want to participate in MakeUofT? (200 words max)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
    ]
