# Generated by Django 3.2.15 on 2024-01-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_application_rsvp"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="birthday",),
        migrations.RemoveField(model_name="application", name="data_agree",),
        migrations.RemoveField(model_name="application", name="q1",),
        migrations.RemoveField(model_name="application", name="q2",),
        migrations.RemoveField(model_name="application", name="q3",),
        migrations.AddField(
            model_name="application",
            name="age",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("22+", "22+"),
                ],
                default=0,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="country",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="devpost",
            field=models.URLField(
                blank=True, help_text="Devpost Profile (Optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="discovery_method",
            field=models.TextField(
                choices=[
                    (None, ""),
                    ("instagram", "Instagram"),
                    ("in class/from a professor", "In Class/From a professor"),
                    ("discord", "Discord"),
                    ("email", "Email"),
                    ("from a friend", "From a friend"),
                    ("other", "Other"),
                ],
                default="",
                help_text="How did you hear about MakeUofT?",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="email_agree",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I authorize MLH to send me pre- and post-event informational emails, which contain free credit and opportunities from their partners.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="github",
            field=models.URLField(
                blank=True, help_text="Github Profile (Optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="how_many_hackathons",
            field=models.TextField(
                choices=[
                    (None, ""),
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5 or more", "5 or more"),
                ],
                default=0,
                help_text="How many hackathons have you been to?",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="linkedin",
            field=models.URLField(
                blank=True, help_text="LinkedIn Profile (Optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="logistics_agree",
            field=models.BooleanField(
                default=False,
                help_text='I authorize you to share my application/registration information with Major League Hacking for event administration, ranking, and MLH administration in-line with the <a href="https://mlh.io/privacy" rel="noopener noreferrer" target="_blank">MLH Privacy Policy</a>. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/blob/main/contest-terms.md" rel="noopener noreferrer" target="_blank">MLH Contest Terms and Conditions</a> and the <a href="https://mlh.io/privacy" rel="noopener noreferrer" target="_blank">MLH Privacy Policy.</a>',
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="program",
            field=models.CharField(
                default="", help_text="Program or Major", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="pronouns",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("she-her", "She/Her"),
                    ("he-him", "He/Him"),
                    ("they-them", "They/Them"),
                    ("she-they", "She/They"),
                    ("he-they", "He/They"),
                    ("no-answer", "Prefer not to Answer"),
                    ("other", "Other"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="what_hackathon_experience",
            field=models.TextField(
                default="",
                help_text="If you’ve been to a hackathon, briefly tell us your experience. If not, describe what you expect to see and experience. (1000 chars. max)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="what_technical_experience",
            field=models.TextField(
                default="",
                help_text="What is your technical experience with software and hardware? (1000 chars. max)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="why_participate",
            field=models.TextField(
                default="",
                help_text="Why do you want to participate in MakeUofT? (1000 chars. max)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="conduct_agree",
            field=models.BooleanField(
                default=False,
                help_text='I have read and agree to the <a href="https://static.mlh.io/docs/mlh-code-of-conduct.pdf" rel="noopener noreferrer" target="_blank">MLH code of conduct</a>.',
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("asian-indian", "Asian Indian"),
                    ("black-african-american", "Black or African American"),
                    ("chinese", "Chinese"),
                    ("filipino", "Filipino"),
                    ("guamanian-chamorro", "Guamanian or Chamorro"),
                    ("hispanic-latino", "Hispanic/Latino/Spanish Origin"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("middle-eastern", "Middle Eastern"),
                    ("native-american", "Native American or Alaskan Native"),
                    ("native-hawaiian", "Native Hawaiian"),
                    ("samoan", "Samoan"),
                    ("vietnamese", "Vietnamese"),
                    ("caucasian", "White / Caucasian"),
                    ("other-asian", "Other Asian (Thai, Cambodian, etc)"),
                    ("other-pacific-islander", "Other Pacific Islander"),
                    ("other", "Other (Please Specify)"),
                    ("no-answer", "Prefer not to answer"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="study_level",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("less-highschool", "Less than Secondary/High School"),
                    ("highschool", "Secondary/High School"),
                    (
                        "undergraduate-twoyears",
                        "Undergraduate University (2 year - community college or similar)",
                    ),
                    ("undergraduate-threeyears", "Undergraduate University (3+ year)"),
                    (
                        "gradschool",
                        "Graduate University (Masters, Professional, Doctoral, etc) ",
                    ),
                    ("postdoctorate", "Post Doctorate"),
                    ("codeschool", "Code School/Bootcamp"),
                    (
                        "other-apprenticeship",
                        "Other Vocational / Trade Program or Apprenticeship",
                    ),
                    ("other", "Other (Please Specify)"),
                    ("not-student", "I'm not currently a student"),
                    ("no-answer", "Prefer not to answer"),
                ],
                max_length=50,
            ),
        ),
    ]
