# Generated by Django 3.2.15 on 2024-01-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20240103_2009"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume_sharing",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I consent to IEEE UofT sharing my resume with event sponsors.",
                null=True,
            ),
        ),
    ]
