# Generated by Django 3.2.15 on 2023-01-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_alter_application_referral_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="custom_choice",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="application",
            name="city",
            field=models.CharField(
                blank=True, help_text="City (Optional)", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country (Optional)", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume_sharing",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I consent to IEEE UofT sharing my resume with event sponsors. (Optional)",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="what_hackathon_experience",
            field=models.TextField(
                help_text="If you’ve been to a hackathon, briefly tell us your experience. If not, describe what you expect to see and experience. (1000 chars. max)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="what_technical_experience",
            field=models.TextField(
                help_text="What is your technical experience with software and hardware? (1000 chars. max)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="why_participate",
            field=models.TextField(
                help_text="Why do you want to participate in MakeUofT? (1000 chars. max)",
                max_length=1000,
            ),
        ),
    ]
