# Generated by Django 3.2.15 on 2023-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_auto_20230116_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("halal", "Halal"),
                    ("vegetarian", "Vegetarian"),
                    ("gluten-Free", "Gluten-free"),
                    ("other but specify", "Other but Specify"),
                ],
                max_length=50,
            ),
        ),
    ]
