# Generated by Django 3.2.15 on 2024-01-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_auto_20240107_1917"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("halal", "Halal"),
                    ("vegetarian", "Vegetarian"),
                    ("gluten-Free", "Gluten-free"),
                    ("other but specify", "Other but Specify"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="tshirt_size",
            field=models.CharField(
                choices=[(None, ""), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
