# Generated by Django 3.2.15 on 2024-01-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20240107_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='sexual_orientation',
            field=models.CharField(choices=[(None, ''), ('straight', 'Heterosexual or straight'), ('gay-lesbian', 'Gay or lesbian'), ('bisexual', 'Bisexual'), ('different', 'Different Identity (Please Specify'), ('no-answer', 'Prefer not to answer')], help_text='Do you consider yourself to be any of the following?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='underrepresented_community',
            field=models.CharField(choices=[(None, ''), ('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], help_text='Do you identify as a part of an underrepresented group in the technology industry?', max_length=1000),
        ),
    ]
