# Generated by Django 3.2.15 on 2023-01-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_auto_20230118_0038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("halal", "Halal"),
                    ("vegetarian", "Vegetarian"),
                    ("gluten-Free", "Gluten-free"),
                    ("other but specify", "Other but Specify"),
                    ("none", "None"),
                ],
                max_length=50,
            ),
        ),
    ]
