export const hackathonName = "MakeUofT 2024";
export const adminGroup = "Hardware Site Admins";
export const minTeamSize = 2;
export const maxTeamSize = 4;
export const hardwareSignOutStartDate = new Date(2024, 1, 12, 11, 59);
export const hardwareSignOutEndDate = new Date(2024, 1, 18, 12, 0);
export const hssTestUserGroup = "HSS Test Users";
export const serverUrl = "https://makeuoft.ca";
export const minProjectDescriptionLength = 60;
