# Generated by Django 3.2.12 on 2023-02-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='breakfast2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='dinner1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='lunch1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='lunch2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='sign_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
